amazon/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', home , name='home'),
    path('signup/', sign__up , name='signup'),
    path('login/', log__in , name='login'),
    path('logout/', log__out , name='logout'),
    path('home/<str:pk>/' , product_detail , name='product_detail' ),  # Sproduct details
    path('my_account/' , my_account , name='my_account' ),  # My account
    # path('edit my account' , edit_my_account , name='edit_my_account' ),  # Edit My account
    path('search result/', search_product, name='search_product'),
    
    path('add_to_cart/<int:id>/', add_to_cart, name='add_to_cart'),
    path('view_cart/<int:id>/', remove_from_cart, name='remove_from_cart'),
    path('view_cart/', view_cart, name='view_cart'), 
    path('my_orders/', my_order, name='my_order'),
    path('checkout/', checkout, name='checkout'),
    path('order_confirmation/', order_confirmation, name='order_confirmation'),
    path('download_bill/<int:id>/', generate_pdf_bill, name='generate_pdf_bill'),
]


 


    

app/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
import uuid


class Products(models.Model):
    product_name=models.CharField(max_length=100, null=True)
    product_details=models.TextField(max_length=150, null=True)
    product_price = models.DecimalField(max_digits=10,null=True, decimal_places=2, default=1) 
    product_image=models.ImageField(upload_to= 'product-images', null=True) 
    create_date=models.DateTimeField(default=timezone.now)

    
    def __str__(self):
        return self.product_name
    
class Profile(models.Model):
    user_address_1=models.CharField(max_length=150, null=True)  
    user_address_2=models.CharField(max_length=150, null=True)
    user_pincode=models.CharField(max_length=6,null=True)
    user_email=models.CharField(max_length=100, null=True)
    user_phone=models.CharField(max_length=10, null=True) 
    var=models.ForeignKey(User, default=0,null=True, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.user_phone
 
class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    items = models.ManyToManyField(Products)
    order_date = models.DateTimeField(auto_now_add=True)   
    total_amount = models.DecimalField(max_digits=10, default=1, decimal_places=2)


class Cart(models.Model):
    user = models.ForeignKey(Profile,on_delete=models.CASCADE, related_name='carts')
    order = models.ForeignKey(Order, null=True, blank=True, on_delete=models.SET_NULL)
    

    def __str__(self):
        return str(self.user)

class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Products, on_delete=models.CASCADE, null=True)
    quantity = models.DecimalField(max_digits=10,null=True, decimal_places=0,default=1)
    total_price = models.DecimalField(max_digits=10, decimal_places=2, default=1)
    var = models.ForeignKey(User, default=1, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.cart)
    
    def save(self, *args, **kwargs):
        self.total_price = self.product.product_price * self.quantity
        super(CartItem, self).save(*args, **kwargs)


class Bill(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, null=True)
    total_amount = models.DecimalField(max_digits=10,  decimal_places=2)
    bill_date = models.DateTimeField(auto_now_add=True)
   

    def __str__(self):
        return f'Bill for Order {self.order.id}'


   


    
      

app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}
    {% endblock %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/responsive_tab.css' %}">
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
</head>
<body>
    <!-- header start -->
    <header>
        <!-- box-1 -->
        <div class="nav-bar">
            <div class="box-1 border">
                <a href="{% url 'home' %}"><img src="{% static 'img/amazon-logo.png' %}"></a>
            </div>
            <!-- box 2 -->
            {% if user.is_authenticated %}
            <div class="box-4 border">
                    <div class="hellouser">
                        <p class="box-4-account">Hi.. {{user.username}}</p>                   
                    </div> 
            </div>
            {% endif %}
            <!-- box-3  Search --> 
            <div class="nav-search">
                <form style="display: flex; justify-content: center;" action="{% url 'search_product' %}" method="get">
                <input type="text"  name="q" class="searchbar" placeholder="Search Products">
                <div class="search-icon">
                    <button type="submit"><i class="fa-solid fa-magnifying-glass"></i></button>
                </div>
            </form>
            </div>
       

            {% if user.is_authenticated %}
            <div class="box-4 border">
                <a href="{% url 'my_account' %}">
                    <div class="hellouser">
                        <p class="box-4-account">My Acount</p>                   
                    </div>
                </a>
            </div>
              <!-- box-5 -->
              <div class="box-5 border">
                <a href="{% url 'my_order' %}">
                    <div>
                        <p class="box-4-account">My Orders</p>
                    </div>
                </a>
            </div>
            <div class="box-4 border">
                <div class="hellouser">
                    <a href="{% url 'logout' %}"><p class="box-4-account">Log out</p></a>                   
                </div>
            </div>
            {% else %}   
            <div class="box-4 border">
                <div class="hellouser">
                    <a href="{% url 'login' %}"><p class="box-4-account">Log in</p></a>                   
                </div>
            </div>         
            {% endif %}
          
            <!-- box-6 -->
            <div class="box-6 border">
                <a href="">
                    <div class="box-6-items">
                        <a href="{% url 'view_cart' %}"><span> <i class="fa-solid fa-cart-shopping"></i></span></a>
                        <p class="box-4-account">Cart</p>
                       <!-- <p>4</p> -->
                    </div>
                </a>
            </div>

        </div>

    </header>
    <!-- header end  -->


<!-- below header start-->
    <div class="belowheader">
        <div class="belowheader-items">
            <a href="{% url 'home' %}"><div class="primedaydeal border" style="display: flex; align-items: center; height: 35px; color: white;" ><p>HOME</p></div></a>
            <a href="{% url 'search_product' %}?name=Shoe"><div class="primedaydeal border" style="display: flex; align-items: center; height: 35px;" ><p>Shoe</p></div></a>
            <a href="{% url 'search_product' %}?name=laptop"><div class="primedaydeal border" style="display: flex; align-items: center; height: 35px;" ><p>Laptop</p></div></a>
            <a href="{% url 'search_product' %}?name=phone"><div class="primedaydeal border" style="display: flex; align-items: center; height: 35px;" ><p>Phone</p></div></a>
            <a href="{% url 'search_product' %}?name=Shirt"><div class="primedaydeal border" style="display: flex; align-items: center; height: 35px;" ><p>Shirt</p></div></a>
                       
        </div>
    </div>
    <!-- end header  -->
    {% block mainn %}


    
    {% endblock %}
    <footer>    
             <div class="copyright">
               <p> Site by Pankaj</p>
            </div>
        </div>
    </footer>
</body>
</html>

app/templates/bill_template.html
<!DOCTYPE html>
<html>
<head>
    <title>Bill</title>
</head>
<body>
    <h1><i>Amazon Service</i></h1>
    <h1>Bill for Order {{ bill.order.id }}</h1>
    <p>Total Amount: Rs. {{ bill.total_amount }}</p>
    <!-- Add more bill details here -->
</body>
</html>

app/templates/cart.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
<title>Home</title>
{% endblock %}

{% block mainn %}
<main class="cart-main">
    <!-- ... (other HTML code) -->

<div class="class-item-outer">
    {% if cart_items %}
    {% for i in cart_items %}
    <div class="cart-items">
        <div class="cart-item-image">            
            <a href="{% url 'product_detail' i.product.id %}">
                <img class="cart-image" style="height: 100px; width: 80px;" src="{{ i.product.product_image.url }}" alt="">              
            </a>
        </div>
        <div>
            <p class="cart-product-name" style="color: white;">{{ i.product.product_name }}</p>
        </div>
        <div class="cart-item-qty">
            <!-- ###################### -->
            <form action="{% url 'view_cart' %}" method="POST">
                {% csrf_token %}
                <div class="cart-item">
                    <input type="number" name="quantity-{{ i.id }}" value="{{ i.quantity }}" min="1" max="10" size="10" >
                    <input type="submit" value="Update Cart">
                </div>
            </form>

          
            <!-- ########################## -->
        </div>
        <div>
            <h3 style="color: white;">{{ i.product.product_price }}</h3>
        </div>
        <div>
            <h3 style="color: white;">{{ i.total_price }}</h3>
        </div>
        <div class="cart-remove">
            <a href="{% url 'remove_from_cart' i.id %}"><button class="add-to-cart-button">remove</button></a> 
        </div>  
    </div>    
    {% endfor %}
</div>
 <div class="cart-checkout">
        <!-- <a href="{% url 'checkout'  %}" class="add-to-cart-button">Checkout</a> -->
        <form method="post" action="{% url 'checkout' %}">
            {% csrf_token %}
            <h2>Shipping Information</h2>
            <label for="shipping_address">Shipping Address:</label>
            <input type="text" id="shipping_address" name="shipping_address" required><br>
    
            <label for="payment_method">Payment Method:</label><br>
            <select id="payment_method" name="payment_method" required>
                <option value="credit_card">Credit Card</option>
                <option value="paypal">PayPal</option>
            </select><br>
    
            <h2>Order Summary</h2>
            <h2>Total Amount: Rs.{{ total_amount }}</h2><br>
    
            <button type="submit" class="add-to-cart-button">Place Order</button>
        </form>
 </div>
    {% else %}
    <img style="margin-top: 5%;" src="{% static  'img/empty-cart.png' %}" alt="">
    {% endif %}
</main>
{% endblock %}

app/templates/confirmation.html
{% extends 'base.html' %}
{% load static %}

{%  block title %}
<title>Home</title>
{% endblock %}

{% block mainn %}
<div style="height: 1000px; text-align: center; margin-top: 2%;">
    <h1>Order Placed</h1> 
    <p>Thank you for your order. Your order has been successfully placed.</p>
    <br>
    <br>
    <h3>Bill has been sent on your Email</h3>
    <p>See <a style="color: blue" href="{% url 'my_order' %}">My Order</a></p>
</div>
  
{% endblock %}

app/templates/edit_my_account.html
{% extends 'base.html' %}
{% load static %}

{%  block title %}
<title>My Account</title>
{% endblock %}

{% block mainn %}

<main class="mainn">
    
    <div class="product-outer-frame">
        <div style="margin-top: 5%;">
        <form  method="POST" action="{% url 'edit_my_account' %}" >
            {% csrf_token %}
            {{ form.as_p }}    
            <input class="btn" type="submit" value="Update" size="40"><br><br>   
        </form>
        </div> 
    </div>
</main>


{% endblock %}

app/templates/home.html
{% extends 'base.html' %}
{% load static %}

{%  block title %}
<title>Home</title>
{% endblock %}

{% block mainn %}
<main class="main">
    
    <div class="product-outer-frame">
        {% for i in data %}
        <div class="product-frame">
            <div class="product-image">
                <a href="{% url 'product_detail' i.id %}"><img style="height: 300px; width: 257px;" src="{{ i.product_image.url }}" alt=""></a>
            </div>
            <div class="price-section">
                <strong>{{ i.product_name }}</strong>
                <strong>{{ i.product_price }}</strong>
            </div>
        </div>
        {% endfor  %} 
        
        {% if zata %}
        {% for i in zata %}
        <div class="product-frame">
            <div class="product-image">
                <a href="{% url 'product_detail' i.id %}"><img style="height: 312px; width: 257px;" src="{{ i.product_image.url }}" alt=""></a>
            </div>
            <div class="price-section">
                <strong>{{ i.product_price }}</strong>
                <strong>{{ i.product_name }}</strong>
            </div>
        </div>
        {% endfor  %}
        {% endif %}
    </div>
 



</main>
{% endblock %}

app/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Log in</title>
    <link rel="stylesheet" href="{% static 'css/login-signup.css' %}">
</head>
<body>
    <div class="outer">
        <div class="frame">
            <form action="" method="POST">
                {% csrf_token %}
                <h2>Login</h2><br>
                <input type="text" placeholder="username" name="username" required><br><br>
                <input type="password" placeholder="password" name="password" required><br><br>
                <button type="submit">Log in</button><br><br>
                <p>Not have an account? <a href="{% url 'signup' %}" class="ml-2">Signup here</a></p>
            </form>
        </div>
    </div>
</body>
</html>

app/templates/my_account.html
{% extends 'base.html' %}
{% load static %}

{%  block title %}
<title>My account</title>
{% endblock %}

{% block mainn %}
<main class="mainn">
    <h2 style="text-align: center;">My Account Details</h2><br>
            <div class="my-account-frame">
                <div>
                    {% if user.is_authenticated %}
                    <h3>Name: {{ user.username }}</h3><br>
                    <strong>Email: </strong>{{ user.email}}<br><br>
                    {% endif %}
                    
                </div>
            </div>
        
</main>
{% endblock %}

app/templates/my_order.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
<title>My Orders</title>
{% endblock %}

{% block mainn %}
<h2>Order Summary</h2>
<main class="cart-main">  
    <div class="class-item-outer">
        {% for order in orders %}
        <div class="cart-items">
            <div class="cart-item-image">             
                    {% for i in order.items.all %}
                    <a href="{% url 'product_detail' i.id %}"><img style="height: 60px; width: 50px;" src="{{ i.product_image.url }}" alt=""> </a>
                    {% endfor %}                    
            </div>
            <div>
                <p style="color: white;"></p>
            </div>
            <div>
                {% for i in order.items.all %}
                <h6 style="color: white; display: inline;">{{ i.product_name }}</h6>
                <h6 style="color: white; display: inline;">   RS. {{ i.product_price }}</h6>
                {% endfor %}
            </div>
            <div>
            {% with bill=order.bill_set.first %}
            {% if bill %}
             <h3><a href="{% url 'generate_pdf_bill' order.id %}">Download Bill PDF</a></h3> 
            {% endif %}
            {% endwith %}
            </div>
            <div class="cart-remove">
                <p style="color: beige;">Order Date: {{ order.order_date }}</p>
                <p style="color:aquamarine">Total Amount: {{ order.total_amount }}</p>
               <p style="color: yellow;">delivery status...</p>
            </div> 
        </div> 
        {% endfor %}    
    </div>  
</main>
{% endblock %}

app/templates/product_detail.html
{% extends 'base.html' %}
{% load static %}

{%  block title %}
<title>Product details</title>
{% endblock %}

{% block mainn %}


<main class="single-main">
    <div class="single-product-outer-frame">
        <div class="single-product-frame">
            <div class="single-product-image">
                <img style="height: 412px; width: 360px;" src="{{ data.product_image.url }}" alt="">
            </div>
            <div class="single-product-detail">
                <div style="height: 80%;">
                    <strong>{{ data.product_price }}</strong><br><br>
                    <p>{{ data.product_details }}</p><br><br>
                </div>

                <div style="height: 20%; margin-left: 10%; min-width: 200px;">     
                    <form method="POST" action="{% url 'add_to_cart' data.id %}">
                        {% csrf_token %}
                        <input hidden type="number" name="quantity" value="1" min="1">
                        <button class="add-to-cart-button" type="submit">Add to cart</button>
                    </form>
                </div>
                <br>           
                <br>           
                <br>           
                <br>           
                <br>           
                <br>           
                <br>           
                <br>           
            </div>    
        </div>
    </div>
</main>
{% endblock %}

app/templates/signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Signup</title>
    <link rel="stylesheet" href="{% static 'css/login-signup.css' %}">
</head>
<body>
    <div class="outer">
        <div class="frame">
            <form action="" method="POST">
                {% csrf_token %}
                <h2>Create Account</h2><br>
                <input type="text" placeholder="username" name="username" required><br><br>
                <p>Enter valid email address to get bill.</p>
                <p>unexist email will not get bill on email.</p><br>
                <input type="email" placeholder="valid email" name="email" required><br><br>
                <input type="password" placeholder="password" name="password1" required><br><br>
                <input type="password" placeholder="password again" name="password2" required><br><br>
                <button type="submit">Sign up</button><br><br>
                <p>Already have an account? <a href="{% url 'login' %}" class="ml-2">Login here</a></p>
            </form>
        </div>
    </div>
</body>
</html>